### ISSUE TITLE
Infinite Loop

### ISSUE THREAD

**Issue by trblft** [ulisesbocchio/spring-boot-security-saml-samples#16]
Hi again, 
Still implementing the -props example.
I now have infinite Loop between those two urls.

> https://localhost:8443/saml/SAMLAssertionConsumer
> https://idp-interne.insee.test/idp/profile/SAML2/POST/SSO

Despite the process seems to work

> 2018-02-08 14:01:37.716 DEBUG 4364 --- [nio-8443-exec-9] o.s.s.saml.storage.HttpSessionStorage    : Storing message a1a3jf8hce4h444b45599988788j298 to session 1529A14836B1EF6B90C436CCA8BF6515
> 2018-02-08 14:01:37.716  INFO 4364 --- [nio-8443-exec-9] o.s.security.saml.log.SAMLDefaultLogger  : AuthNRequest;SUCCESS;0:0:0:0:0:0:0:1;https://localhost:8443;https://idp-interne.insee.test/idp/shibboleth;;;

In this page they say it may come from userDetails implementation.
https://stackoverflow.com/questions/36126760/infinite-loop-for-saml-request-in-spring-saml

My application.yml file looks like
```
spring:
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gco
    username: gco_user
    password: gco1234
  thymeleaf:
    cache: false
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
gco:
  queries:
    agents-query: select idep, password, active from agent where idep=?
    roles-query: select a.idep, r.name from agent a inner join agent_role ar on(a.id=ar.agent_id) inner join role r on(ar.role_id=r.id) where a.idep=?
logging:
  level:
    org:
      springframework: 
        security:
          saml: DEBUG
security:
  user:
    name: user
    password: password
saml:
  sso:
    discovery-processing-url: https://id-provider.insee.test/samlds
    metadata-generator:
      entity-id: https://localhost:8443/
    default-success-url: /home
    idp-selection-page-url: /idpselection
    logout:
      default-target-url: /
    idp:
      metadata-location: classpath:/config/metadata/IDP/idp-interne.insee.test.xml
      local-metadata-location: classpath:/config/metadata/SP/SPMetadata.xml
    metadata-manager:
      refresh-check-interval: 0
    extended-metadata:
      idp-discovery-enabled: true
    key-manager: 
      store-location: classpath:/config/certificate/keystore
      store-pass: secret
      default-key: saml
      key-passwords:
        saml: secret
```
